[build]
  publish = "."

[[forms]]
  name = "simulacao-antecipacao"
  
  [forms.settings]
    to = ["gabriel.sarkis.1@gmail.com"]
    subject = "Nova Simulação de Antecipação - Impulsa"
    
  [forms.templates]
    success = "/thank-you.html"
    failure = "/error.html"